### PR TITLE
fix(examples): fix pagination total

### PR DESCRIPTION
**Pull request by btea**

### CODE REVIEW

**Comment by pengYYYYY** [comment]
Thanks

**Comment by pengYYYYY** [comment]
snapshot need to be updated: npm run test:update

**Comment by btea** [comment]
ok, I'll update

**Comment by btea** [comment]
Sorry, I failed to update the snapshot.  When I run `npm run test:update`, the following errors occurs.

```sh
Cannot find module '../../_common/style/web/components/**/_index.less'
...
```

**Comment by pengYYYYY** [comment]
we have a git submodule to manage common logic/style/md, you need to run `git submodule init && git submodule update` .

**Comment by btea** [comment]
ok, I see. I have updated

**Review by pengYYYYY — APPROVED** [review]
LGTM

**Pull request merged**
