### PR TITLE
fix(dialog): add missing null type

### LINKED ISSUE #4400: [Dialog] 按钮的属性设置为null报类型错误
### tdesign-vue-next 版本

1.9.7

### 重现链接

_No response_

### 重现步骤

image

### 期望结果

_No response_

### 实际结果

_No response_

### 框架版本

_No response_

### 浏览器版本

_No response_

### 系统版本

_No response_

### Node版本

_No response_

### 补充说明

_No response_

### PR DESCRIPTION
**Pull request by chouchouji**
### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

- #4400
- https://github.com/Tencent/tdesign-vue-next/issues/3919
### 📝 更新日志

- fix(Dialog): 修复 `cancelBtn` 和 `confirmBtn` 设置为`null` 的类型问题

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

### CODE REVIEW

**Comment by uyarn** [comment]
@chouchouji thanks for you PR! but didn't you reproduce it, it's normal in my IDE
image

**Comment by uyarn** [comment]
> @chouchouji thanks for you PR! but didn't you reproduce it? it's normal in my IDE image

I see, it's because of the strictNullChecks of my tsconfig is `false` :)

**Comment by gangchn** [comment]
So it is look like reasonable that set `null` as one of property `cancelBtn` type, because it is a nullable property and we also explicitly describe that it can be set to null in comment.

**Comment by uyarn** [comment]
would you mind fixing `confirmBtn` as well ?

**Comment by chouchouji** [comment]
> would you mind fixing `confirmBtn` as well ?

I will complete it. Thanks for your review!

**Comment by chouchouji** [comment]
> would you mind fixing `confirmBtn` as well ?

done

**Review by uyarn — APPROVED** [review]

**Pull request merged**
